docs: Prefer analyze over analyse
k8sgpt-ai/docs pull request #42
Opened 2023-05-14 16:06 UTC by cubxxw

Link k8sgpt-ai/k8sgpt/issues/409 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2023-05-14 16:14 UTC, matthisholleville approved these changes
LGTM

2023-05-14 20:25 UTC, AlexsJones commented on docs/getting-started/getting-started.md
> +## analyze your cluster
```suggestion
## Analyze your cluster
```

2023-05-14 20:25 UTC, AlexsJones requested changes
One suggestion

2023-05-15 05:39 UTC, AlexsJones approved these changes

2023-05-15 05:39 UTC, AlexsJones approved these changes

2023-05-15 05:40 UTC, merged