feat: add Amazon SageMaker backend dokumentation
k8sgpt-ai/docs pull request #79
Opened 2023-12-05 07:24 UTC by dkuroczk

This PR adds documentation about Amazon SageMaker backend with example how to deploy Amazon SageMaker and how to configure backend.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

2023-12-22 13:23 UTC, AlexsJones approved these changes

2023-12-22 13:24 UTC, AlexsJones requested changes

2023-12-22 13:24 UTC, AlexsJones commented on docs/reference/providers/backend.md
> +- Now you are ready to analyze with the Azure OpenAI backend:
This should be sagemaker?

2023-12-22 13:24 UTC, AlexsJones commented on docs/reference/providers/backend.md
> +Example how to deploy Amazon SageMaker with cdk is availabel in [llm-sagemaker-jumpstart-cdk](https://github.com/zaremb/llm-sagemaker-jumpstart-cdk) repo.
Spelling of "availabel" is available

2023-12-22 19:01 UTC, dkuroczk commented on docs/reference/providers/backend.md
> +- Now you are ready to analyze with the Azure OpenAI backend:
🤦 Fixed

2023-12-22 19:01 UTC, dkuroczk commented on docs/reference/providers/backend.md
> +Example how to deploy Amazon SageMaker with cdk is availabel in [llm-sagemaker-jumpstart-cdk](https://github.com/zaremb/llm-sagemaker-jumpstart-cdk) repo.
done

2023-12-23 07:50 UTC, AlexsJones approved these changes

2023-12-27 13:14 UTC, dkuroczk commented
Commit signature fixed ready to be merged

2023-12-27 17:36 UTC, AlexsJones approved these changes

2023-12-27 17:36 UTC, merged